# Default values for safra-device-stats Helm chart

global:
  imageRegistry: ""
  imagePullSecrets: []

# Statistics API Configuration
statisticsApi:
  name: statistics-api
  image:
    repository: safra-statistics-api
    tag: "1.0.0"
    pullPolicy: Always
  
  replicaCount: 3
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rate-limit: "100"
      nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    hosts:
      - host: api.safra-device-stats.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: statistics-api-tls
        hosts:
          - api.safra-device-stats.local
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

# Device Registration API Configuration
deviceRegistrationApi:
  name: device-registration-api
  image:
    repository: safra-device-registration-api
    tag: "1.0.0"
    pullPolicy: Always
  
  replicaCount: 2
  
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

# PostgreSQL Configuration
postgresql:
  enabled: true
  auth:
    database: safra_device_stats
    username: safra_user
    password: safra_password
  primary:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

# External PostgreSQL (when postgresql.enabled is false)
externalDatabase:
  host: ""
  port: 5432
  database: safra_device_stats
  username: safra_user
  password: safra_password

# Security Configuration
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

podSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

# Network Policies
networkPolicies:
  enabled: true

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Monitoring
monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: false

# Environment
environment: production

# JVM Configuration
jvm:
  opts: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"