# Safra Bank Statistics API Configuration
# DevSecOps-focused Spring Boot configuration
# Updated: Fixed database hostname configuration for Kubernetes deployment

server:
  port: 8080
  servlet:
    context-path: /
  # Security headers for DevSecOps
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: statistics-api
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:safra_device_stats}
    username: ${DB_USERNAME:safra_user}
    password: ${DB_PASSWORD:safra_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Connection pool settings for performance and security
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        # Security: disable SQL comments
        use_sql_comments: false
    open-in-view: false

  # Security configuration
  security:
    require-ssl: false # Set to true in production

# Custom application properties
device:
  registration:
    api:
      url: ${DEVICE_REGISTRATION_API_URL:http://localhost:8081}

# Actuator configuration for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Logging configuration
logging:
  level:
    com.safra.bank: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

---
# Production profile
spring:
  config:
    activate:
      on-profile: production
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:safra_device_stats}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    require-ssl: true

server:
  port: 8080
  # Production security headers
  servlet:
    session:
      cookie:
        secure: true
        http-only: true

device:
  registration:
    api:
      url: ${DEVICE_REGISTRATION_API_URL:http://device-registration-api:8081}

logging:
  level:
    com.safra.bank: INFO
    org.springframework: WARN
    org.hibernate: WARN

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:safra_device_stats}
    username: ${DB_USERNAME:safra_user}
    password: ${DB_PASSWORD:safra_password}

device:
  registration:
    api:
      url: http://device-registration-api:8081