apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: safra-device-stats
  labels:
    app: postgres
    tier: database
type: Opaque
data:
  # Base64 encoded values
  # Default password: safra_password (base64: c2FmcmFfcGFzc3dvcmQ=)
  # Change this in production!
  POSTGRES_PASSWORD: c2FmcmFfcGFzc3dvcmQ=