apiVersion: v1
kind: Service
metadata:
  name: device-registration-api
  namespace: safra-device-stats
  labels:
    app: device-registration-api
    tier: backend
    component: internal-api
spec:
  type: ClusterIP  # Internal access only
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: device-registration-api
    tier: backend